#!/usr/bin/env ruby

require_relative '../lib/epub_utils'

def extract_metadata_optimized(epub_path)
  metadata = EpubUtils.extract_metadata(epub_path)
  return nil unless metadata
  [metadata[:title], metadata[:author]]
end

def rename_epub_optimized(epub_path)
  return unless epub_path.end_with?('.epub') && File.exist?(epub_path)
  
  title, author = extract_metadata_optimized(epub_path)
  return unless title

  filename = "#{title}#{author ? " - #{author}" : ''}"
  filename = EpubUtils.sanitize_filename(filename) + '.epub'
  
  new_path = File.join(File.dirname(epub_path), filename)
  return if File.exist?(new_path)
  
  File.rename(epub_path, new_path)
  puts "#{File.basename(epub_path)} -> #{filename}"
end

ARGV.each { |file| rename_epub_optimized(file) }
puts "Usage: epub-renamer file.epub" if ARGV.empty?